CREATE TABLE admin(
  ID INT(11) AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(120),
  EMAIL VARCHAR(120),
  PASSWORD VARCHAR(120),
  PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE suscribers(
  ID INT(11) AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(120),
  EMAIL VARCHAR(120),
  PASSWORD VARCHAR(120),
  PRIMARY KEY (ID)
) ENGINE = InnoDB;

SELECT * FROM admin;
INSERT INTO admin(NAME, EMAIL, PASSWORD) VALUES ('admin', 'example@mail.ru', md5('hello_666'));
DROP TABLE admin;